### ISSUE TITLE
Vim fails to source `defaults.vim`?

### ISSUE THREAD

**Issue by sincere267** [vim/vim-appimage#58] opened 2023-09-10 04:02 UTC
```bash
$ ./Vim-v9.0.1885.glibc2.29-x86_64.AppImage
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

**Comment by chrisbra** [comment] 2023-09-10 07:37
duplicate of #55 should be fixed by #56

**Closed by chrisbra** 2023-09-10 07:37 UTC

**Comment by sincere267** [comment] 2023-09-11 01:47
OK, it has been fixed in `Vim-v9.0.1894.glibc2.29-x86_64.AppImage`.
